### ISSUE TITLE
Already solved?

### ISSUE THREAD

**Issue by oliviertassinari** [STRML/react-document-events#1]
Are you looking for something like https://github.com/oliviertassinari/react-event-listener?

**Comment by STRML** [comment]
:shipit: I am!

**Comment by STRML** [comment]
I've about finished it anyhow... may as well publish it.

**Comment by oliviertassinari** [comment]
Ahah, I'm curious to see it then :D.

**Comment by STRML** [comment]
Published - see what you think.
